### ISSUE TITLE
problem with mail to links

### ISSUE THREAD

**Issue by topotato** [AndiDittrich/WordPress.Cryptex#2]
Hi, I have problems.
When there is an email with "mailto" tag 
for example <a href="mailto:abc@example.com">abc@example.com</a>

Cryptex will change it to two email and a "> in the middle of it
Can you please tkae a look.

Thanks

**Comment by AndiDittrich** [comment]
## The short Answer

Don't use the Autodetect feature togehter with _mailto:_ links. 
Cryptex is designed for the intermediate WordPress User which did not use self-written HTML within a post and need a "out-of-the-box" solution.
In this case Cryptex will automatically add the _mailto:_ functionality including **javascript based obfuscation** of the mailto link

**Example - Before Autodetection**

``` html
<p>Lorem ipsum dolor sit amet, consetetur email@example.com sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</p>
```

**After Address Transformation**
The whole address is replaced by some html code to display the generated images. 
Additionally the Cryptex Javascript Engine is adding the **mailto:** functionality without the need of an `a` tag with a cleartext E-Mail Address (which can be grabed)!
It's an essential part of the Cryptex Plugin.

``` html
<p>Lorem ipsum dolor sit amet, consetetur <span rel="aef871bc12..." class="cryptex"><img class="CryptexImg" src="..." /></span> sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</p>
```

## The long Answer

To understand what's happened in your case we have to take a look under the hood:
The Autodetect Filter is using the following Regular Expressions to find EMail Addresses within the users content.
These Expression is applied to all major content filters (`the_content`, `get_the_excerpt`, ..) **after** shortcodes are executed.

``` php
private $_detectionPattern = '/\b([a-z0-9_\.+-]+@[\da-z\.-]+\.[a-z]{2,23})\b/i'`;
```

You see, it's not very complex and did not match all types of international e-mail addresses - on the other hand, it's very efficient & performant.

And well... it will also match mailto:(email@address.com) - the address part will be replaced by the Cryptex images (html code). That's the issue in your case.
But the Plugin is especially designed to protect e-mail address hyperlinks - and this can't be done by using a **mailto:** hyperlink (the email address has to be in cleartext, otherwise the browser can't open the EMail client). 

### What's happend

**Before Autodetection** - 2 Addresses will matched

``` html
<a href="mailto:user@example.tld">user@example.tld</a>
```

**After** - Both Addresses are transformed
The `href` attribute is broken because of the added html code

``` html
<a href="mailto:<span rel="">....</span>"><span rel="">....</span></a>
```

Theoretically i can modify the Autodetection filter to completly exclude `a` tags. 
But this will be very performance hungry because of 2 complex Regular Expression which have to be applied to the content on every request.

## Finally

Therefore you should avoid to use handwritten links with **mailto** because Cryptex can do this by itself.
